model_identifier=agc_9busSystem_noSecondaryCtrl
shared_instance_name=AGC_9BUSSYSTEM_NOSECONDARYCTRL
fmu_dir=../power_system_model_fmu_extracted

# Settings for emulated processing time of FMU-attached devices. 
processing_time_const_ns=1090000
processing_time_mean_ns=2539000
processing_time_std_dev_ns=6446521

# Settings for sending data to the client device.
send_data=true
send_data_interval_s=0.02
send_data_endpoints=set(1586->1584,1587->1584,1588->1584)

# General settings related to co-simulation of FMU.
start_time_in_s=0.
comm_step_size_in_s=1e-4
logging_on=false

# Settings for writing FMU results to file.
fmu_res_write=true
fmu_res_write_period_in_s=0.001
fmu_res_filename=agc_9busSystem_noSecondaryCtrl.csv
fmu_res_varnames=list(V1_ref_delta,V2_ref_delta,V3_ref_delta,P1_set_inv,P2_set_inv,P3_set_inv,V1_ref_bs,V2_ref_bs,V3_ref_bs,f1_bs,f2_bs,f3_bs,P1_bs,P2_bs,P3_bs,Q1_bs,Q2_bs,Q3_bs,phasediff12,phasediff13,phasediff23,I1_bs,I2_bs,I3_bs,V1_bs,V2_bs,V3_bs,V_a_bus1,V_b_bus1,V_c_bus1,V_a_bus2,V_b_bus2,V_c_bus2,V_a_bus3,V_b_bus3,V_c_bus3,V_a_bus4,V_b_bus4,V_c_bus4,V_a_bus5,V_b_bus5,V_c_bus5,V_a_bus6,V_b_bus6,V_c_bus6,V_a_bus7,V_b_bus7,V_c_bus7,V_a_bus8,V_b_bus8,V_c_bus8,V_a_bus9,V_b_bus9,V_c_bus9)
