simulation_end_time_ns=25000000000
simulation_seed=593721093

satellite_network_dir="../stars_agc_scenario"
satellite_network_routes_dir="../stars_agc_scenario/dynamic_state_50ms_for_25s"
dynamic_state_update_interval_ns=50000000

isl_data_rate_megabit_per_s=10000.0
isl_max_queue_size_pkts=100000
gsl_data_rate_megabit_per_s=10000.0
gsl_max_queue_size_pkts=100000

enable_isl_utilization_tracking=true
isl_utilization_tracking_interval_ns=1000000000

tcp_socket_type=TcpNewReno

## Extra processing time to emulate real-world packet delays for ground-satellite-links (GSL)
## data fit: k = 1., scale = 2.539 -> mean_ns = 2539000, std_dev_ns = 6446521, const_ns = 1090000
gsl_processing_time_const_ns=1090000
gsl_processing_time_mean_ns=2539000
gsl_processing_time_std_dev_ns=6446521

## Define STARLINK ground station
reroute_node_id=1585

## Extra processing time to emulate real-world packet delays in STARLINK ground station
## data fit backbone network (BB): k = 1., scale = 1.625
## data fit ground-satellite-links (GSL): k = 1., scale = 2.539
## combined gamma distribution parameters: alpha: 1.962, beta: 2.104 -> mean_ns = 4128048, std_dev_ns = 8685413, const_ns = 1090000
starlink_gs_processing_time_const_ns=1090000
starlink_gs_processing_time_mean_ns=4128048
starlink_gs_processing_time_std_dev_ns=8685413

## Add error model (packet loss) to STARLINK ground station
starlink_gs_fault_rate=0.0006977227557738693
starlink_gs_recovery_rate=0.34816365513116077

## Define endpoints
enable_device_clients=true
send_devices_interval_ns=20000000
devices_endpoint_pairs=set(1584->1586,1584->1587,1584->1588)

## Extra processing time to emulate real-world packet delays for endpoints (GSL)
## data fit: k = 1., scale = 2.539 -> mean_ns = 2539000, std_dev_ns = 6446521, const_ns = 1090000
send_devices_processing_time_const_ns=1090000
send_devices_processing_time_mean_ns=2539000
send_devices_processing_time_std_dev_ns=6446521

enable_fmu_shared_devices=true
fmu_config_files=map(agc_busses:agc-9busSystem-noSecondaryCtrl-fmu.properties)
agc_busses=set(1586,1587,1588)

agc_central_ctrl_period_ns=20000000
## STABLE
# agc_central_kp_f = 0.0
# agc_central_ki_f = 1.0
# agc_central_ki_Q = 0.3
# agc_central_kp_Q = 0.1
## UNSTABLE
agc_central_kp_f = 5.0 
agc_central_ki_f = 10.0
agc_central_kp_Q = 1.0
agc_central_ki_Q = 3.0